name: pre-process
description: checkout, lowercase, setup-buildx, login GHCR, run if_clean
inputs:
  remainGB:
    description: remain disk space in GB
    required: false
    default: "7"
  DOCKERHUB_USERNAME:
    description: Dockerhub username for lowering case
    required: true
  GITHUB_TOKEN:
    description: Github token for GHCR login
    required: true
outputs:
  owner:
    description: Lowercased repo owner
    value: ${{ steps.lower.outputs.owner }}
  actor:
    description: Lowercased actor
    value: ${{ steps.lower.outputs.actor }}
  dockerhub:
    description: Lowercased dockerhub username
    value: ${{ steps.lower.outputs.dockerhub }}
runs:
  using: "composite"
  steps:
    - run: df -h
      shell: bash
    
    - name: A→a lowercased
      id: lower
      run: |
        echo "owner=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
        echo "actor=${GITHUB_ACTOR,,}" >> $GITHUB_OUTPUT
        echo "dockerhub=${DOCKERHUB_USERNAME,,}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        DOCKERHUB_USERNAME: ${{ inputs.DOCKERHUB_USERNAME }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ steps.lower.outputs.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}

    - uses: ./.github/actions/if_clean
      with:
        remainGB: ${{ inputs.remainGB }}