name: "Check Disk and CleanupðŸ§¹"
description: "Check disk space and cleanup if low"
inputs:
  remain_gb:
    description: "At least remain ? GB of disk space"
    required: false
    default: "7"
runs:
  using: "composite"
  steps:
    - name: Check disk space
      id: check_space
      run: |
        available=$(df / | tail -1 | awk '{print $4}')  # èŽ·å–å¯ç”¨å—æ•°ï¼ˆ1K å—ï¼‰
        available_gb=$((available / 1024 / 1024))  # è½¬æ¢ä¸º GB
        threshold=${{ inputs.remain_gb }}
        if [ $available_gb -lt $threshold ]; then
          echo "low_space=true" >> $GITHUB_OUTPUT
        else
          echo "low_space=false" >> $GITHUB_OUTPUT
        fi
        df -h
      shell: bash

    - uses: rokibhasansagar/slimhub_actions@main
      if: steps.check_space.outputs.low_space == 'true'
      with:
        retain: "docker_buildkit"
