/** mocap install/calc/file-upload task start/pause/stop */
syntax = "proto3";

package v1;

import "buf/validate/validate.proto";
import "google/protobuf/any.proto";

message TaskRequest {
  string id = 1;
}

message Current {
  /** systemd status */
  string status = 1 [(buf.validate.field).string = {
    in: [
      "dead", // done
      "waiting",
      "running",
      "failed"
    ]
  }];
  optional float count = 2;
}

message Task {
  string id = 1;
  optional string parent_id = 2;
  string title = 3;
  string desc = 4;
  /** position in queue */
  int32 priority = 5;
  map<string, Current> current = 6;
  optional float total = 7;
  optional string unit = 8;
  optional google.protobuf.Any from = 9; // TODO
  optional google.protobuf.Any to = 10;
}

message GetResponse {
  repeated Task tasks = 1;
}

service TaskService {
  rpc Get(Task) returns (GetResponse) {}
}
