[workspace]
channels = ["conda-forge"]
platforms = ["linux-64"] # "osx-arm64", "osx-64" 
version = "2025.07.06"
[environments]
default = ["gpu"]

[feature.gpu.system-requirements]
cuda = "12.1"

[dependencies]
platformdirs = "*" 
python = "3.10.*" # share with gvhmr, optional
toml = "*" 

cython = "*"
dill = "*"
einops = "*"
gdown = "*"
hydra-core = "*"
joblib = "*"
matplotlib = "*"
mmcv = "==1.3.9"
motmetrics = "*"
numpy = "*"
open3d = "*"
opencv = "*"
pandas = "==1.4.0"
pyrender = "*"
pyyaml = "*"
scikit-image = "*"
scikit-image = "*"
scipy = "*"
tensorboard = "*"
timm = "==0.4.9"
tqdm = "*"
xtcocotools = "*"
# setuptools==59.5.0
[pypi-dependencies]
chumpy = {git = "https://github.com/mattloper/chumpy"}
configer = {git = "https://github.com/nghorbani/configer"}

imageio-ffmpeg = "*"
smplx = "*"
torchgeometry = "0.1.2"

dyn_hamr = {path = "./dyn-hamr", editable = true}
[feature.gpu.pypi-dependencies]
torch = {version = "==2.3.0", index = "https://download.pytorch.org/whl/cu121"}
torch-scatter = {version = "==2.1.0", index = "https://pytorch-geometric.com/whl/torch-2.3.0+cu121.html"}
torchvision = {version = "==0.18.0", index = "https://download.pytorch.org/whl/cu121"}
[feature.cpu.pypi-dependencies]
torch = {version = "==2.3.0", index = "https://download.pytorch.org/whl/cpu"}
torch-scatter = {version = "==2.1.0", index = "https://pytorch-geometric.com/whl/torch-2.3.0+cpu.html"}
torchvision = {version = "==0.18.0", index = "https://download.pytorch.org/whl/cpu"}
