[workspace]
channels = ["conda-forge"]
platforms = ["linux-64"] # "osx-arm64", "osx-64" 
version = "2025.07.06"
[environments]
default = ["gpu"]

[feature.gpu.system-requirements]
cuda = "12.1"

[dependencies]
platformdirs = "*" 
python = "3.10.*" # share with gvhmr, optional
toml = "*" 

dill = "*"
einops = "*"
huggingface_hub = "*"
opencv = "*"
scikit-image = "*"
[pypi-dependencies]
chumpy = {git = "https://github.com/mattloper/chumpy"}
smplx = "*"
timm = "*"
ultralytics = ">=8.1.34"

# wilor_mini = {git = "https://github.com/warmshao/WiLoR-mini"}
wilor_mini = {path = ".", editable = true}
[feature.gpu.pypi-dependencies]
torch = {version = "==2.3.0", index = "https://download.pytorch.org/whl/cu121"}
torchvision = {version = "==0.18.0", index = "https://download.pytorch.org/whl/cu121"}
[feature.cpu.pypi-dependencies]
torch = {version = "==2.3.0", index = "https://download.pytorch.org/whl/cpu"}
torchvision = {version = "==0.18.0", index = "https://download.pytorch.org/whl/cpu"}
