[workspace]
channels = ["nvidia", "pytorch", "conda-forge"]
platforms = ["linux-64"] # "osx-arm64", "osx-64" 
version = "2025.6.13"
[environments]
default = ["wilor", "gpu", "dev"]

[feature.gpu.system-requirements]
cuda = "12.1"

[feature.wilor.dependencies]
# share with gvhmr
python = "3.10.*"
torch = {version = "==2.3.0", index = "https://download.pytorch.org/whl/cu121"}
torchvision = {version = "==0.18.0", index = "https://download.pytorch.org/whl/cu121"}

chumpy = {git = "https://github.com/mattloper/chumpy"}
dill = "*"
einops = "*"
huggingface_hub = "*"
opencv = "*"
scikit-image = "*"
smplx = "*"
timm = "*"
ultralytics = ">=8.1.34"

[feature.wilor.pypi-dependencies]
wilor_mini = {git = "https://github.com/warmshao/WiLoR-mini"}
[feature.dev.pypi-dependencies]
mirror_cn = {git = "https://github.com/AClon314/mirror-cn"}

# [pypi-options]
# extra-index-urls = [
#   "https://pypi.tuna.tsinghua.edu.cn/simple",
# ]
# index-url = "https://mirrors.aliyun.com/pypi/simple"
