from mocap_wrapper.lib import *
from _typeshed import Incomplete
from mocap_wrapper.Gdown import google_drive as google_drive
from mocap_wrapper.logger import getLogger as getLogger
from typing import Literal

Log: Incomplete
ENV: str
PACKAGES: Incomplete
BINS: Incomplete
TYPE_SHELLS: Incomplete
SHELLS: Tuple[TYPE_SHELLS]
TYPE_PY_MGRS: Incomplete
PY_MGRS: Tuple[TYPE_PY_MGRS]
SU: Incomplete
TYPE_PKG_ACT: Incomplete
PKG_MGRS: dict[str, dict[TYPE_PKG_ACT, str]]

def remove_if_p(path: str, progress: sp.Popen): ...
def get_py_mgr() -> TYPE_PY_MGRS | None: ...
def get_shell(): ...
def get_pkg_mgr(): ...
def pkg(action: TYPE_PKG_ACT, package: list[str] = [], **kwargs): ...
def i_pkgs(**kwargs): ...
def i_mamba(require_restart: bool = True, **kwargs) -> None: ...
def get_envs(manager: str = 'mamba', **kwargs): ...
def mamba(cmd: str = '', py_mgr: TYPE_PY_MGRS = 'mamba', env=..., python: str = '', txt: Literal['requirements.txt'] | str = '', pkgs=[], **kwargs): ...
def txt_from_self(filename: str = 'requirements.txt'): ...
def txt_pip_retry(txt: str, tmp_dir=..., env=...): ...
def itmd_coro(Dir=..., url: str = 'https://download.is.tue.mpg.de/download.php?domain=smpl&sfile=SMPL_python_v.1.1.0.zip', referer: str = 'https://smpl.is.tue.mpg.de/', PHPSESSID: str = '26-digits_123456789_123456', user_agent: str = 'Transmission/2.77', **kwargs): ...
async def itmd_full(From: str = 'SMPL_python_v.1.1.0/smpl/models/*', to: str = 'smpl', **kwargs): ...
async def i_smpl(Dir=..., PHPSESSIDs: dict = {'smpl': '', 'smplx': ''}, user_agent: str = 'Transmission/2.77', duration=..., **kwargs) -> list['aria2p.Download']: ...
async def i_dpvo(Dir=..., env=..., **kwargs): ...
async def install(mods, **kwargs): ...
def clean() -> None: ...

SHELL: Incomplete
PKG_MGR: Incomplete
PY_MGR: Incomplete
