name: CI
on:
  workflow_dispatch:

  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #  Update python version matrix compatible with your project
        python: ["3.13"]
        # python: ["3.11", "3.12", "3.13"]

    env:
      #  Use API Key from GA's environment variables for testing. You can remove this line if you don't need it.
      SERVICE_API_KEY: ${{ secrets.SERVICE_API_KEY }}

    steps:
      #  This will remove unnecessary files to free up space. This has done because some package needs more space to install. e.g.) torch
      - name: Clean up space for action
        run: rm -rf /opt/hostedtoolcache || true

      - uses: actions/checkout@v4

      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ matrix.python }}

      - name: (pre-install mocap-wrapper)
        run: python src/mocap_wrapper/install/pixi.py -y #| tee ./.log/init.log

      - name: set CN mirror
        if: ${{ env.ACT == 'true' }}
        run: grep -q "mirror" /etc/apt/sources.list || curl -I https://www.google.com/ --max-time 4 || bash <(curl -sSL https://gitee.com/SuperManito/LinuxMirrors/raw/main/ChangeMirrors.sh) --source mirrors.aliyun.com --protocol http --use-intranet-source false --backup true --upgrade-software false --clean-cache false --ignore-backup-tips

      - name: (install 7z,aria2c,gvhmr,wilor) mocap --install
        run: ~/.venv/bin/mocap --install -b '' # 2>&1 | tee ./.log/install.log

      #  `-rs` flag is used to debug for the test failure
      - name: pytest
        run: ~/.pixi/bin/pixi run python -m pytest -rs tests #| tee ./.log/test.log
